/*
 * This file is generated by jOOQ.
 */
package com.mayuran19.mms.jooq;


import com.mayuran19.mms.jooq.tables.PlatformUsers;
import com.mayuran19.mms.jooq.tables.TenantUsers;
import com.mayuran19.mms.jooq.tables.Tenants;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_PLATFORM_USERS_EMAIL = Internal.createIndex(DSL.name("idx_platform_users_email"), PlatformUsers.PLATFORM_USERS, new OrderField[] { PlatformUsers.PLATFORM_USERS.EMAIL }, false);
    public static final Index IDX_PLATFORM_USERS_IS_ACTIVE = Internal.createIndex(DSL.name("idx_platform_users_is_active"), PlatformUsers.PLATFORM_USERS, new OrderField[] { PlatformUsers.PLATFORM_USERS.IS_ACTIVE }, false);
    public static final Index IDX_PLATFORM_USERS_USERNAME = Internal.createIndex(DSL.name("idx_platform_users_username"), PlatformUsers.PLATFORM_USERS, new OrderField[] { PlatformUsers.PLATFORM_USERS.USERNAME }, false);
    public static final Index IDX_TENANT_USERS_EMAIL = Internal.createIndex(DSL.name("idx_tenant_users_email"), TenantUsers.TENANT_USERS, new OrderField[] { TenantUsers.TENANT_USERS.EMAIL }, false);
    public static final Index IDX_TENANT_USERS_STATUS = Internal.createIndex(DSL.name("idx_tenant_users_status"), TenantUsers.TENANT_USERS, new OrderField[] { TenantUsers.TENANT_USERS.STATUS }, false);
    public static final Index IDX_TENANT_USERS_TENANT_ID = Internal.createIndex(DSL.name("idx_tenant_users_tenant_id"), TenantUsers.TENANT_USERS, new OrderField[] { TenantUsers.TENANT_USERS.TENANT_ID }, false);
    public static final Index IDX_TENANTS_SLUG = Internal.createIndex(DSL.name("idx_tenants_slug"), Tenants.TENANTS, new OrderField[] { Tenants.TENANTS.SLUG }, false);
    public static final Index IDX_TENANTS_STATUS = Internal.createIndex(DSL.name("idx_tenants_status"), Tenants.TENANTS, new OrderField[] { Tenants.TENANTS.STATUS }, false);
}
