/*
 * This file is generated by jOOQ.
 */
package com.mayuran19.mms.jooq;


import com.mayuran19.mms.jooq.tables.PlatformUsers;
import com.mayuran19.mms.jooq.tables.TenantUsers;
import com.mayuran19.mms.jooq.tables.Tenants;
import com.mayuran19.mms.jooq.tables.records.PlatformUsersRecord;
import com.mayuran19.mms.jooq.tables.records.TenantUsersRecord;
import com.mayuran19.mms.jooq.tables.records.TenantsRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PlatformUsersRecord> PLATFORM_USERS_EMAIL_KEY = Internal.createUniqueKey(PlatformUsers.PLATFORM_USERS, DSL.name("platform_users_email_key"), new TableField[] { PlatformUsers.PLATFORM_USERS.EMAIL }, true);
    public static final UniqueKey<PlatformUsersRecord> PLATFORM_USERS_PKEY = Internal.createUniqueKey(PlatformUsers.PLATFORM_USERS, DSL.name("platform_users_pkey"), new TableField[] { PlatformUsers.PLATFORM_USERS.ID }, true);
    public static final UniqueKey<PlatformUsersRecord> PLATFORM_USERS_USERNAME_KEY = Internal.createUniqueKey(PlatformUsers.PLATFORM_USERS, DSL.name("platform_users_username_key"), new TableField[] { PlatformUsers.PLATFORM_USERS.USERNAME }, true);
    public static final UniqueKey<TenantUsersRecord> TENANT_USERS_PKEY = Internal.createUniqueKey(TenantUsers.TENANT_USERS, DSL.name("tenant_users_pkey"), new TableField[] { TenantUsers.TENANT_USERS.ID }, true);
    public static final UniqueKey<TenantsRecord> TENANTS_PKEY = Internal.createUniqueKey(Tenants.TENANTS, DSL.name("tenants_pkey"), new TableField[] { Tenants.TENANTS.ID }, true);
    public static final UniqueKey<TenantsRecord> TENANTS_SLUG_KEY = Internal.createUniqueKey(Tenants.TENANTS, DSL.name("tenants_slug_key"), new TableField[] { Tenants.TENANTS.SLUG }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<TenantUsersRecord, TenantsRecord> TENANT_USERS__FK_TENANT_USERS_TENANT_ID = Internal.createForeignKey(TenantUsers.TENANT_USERS, DSL.name("fk_tenant_users_tenant_id"), new TableField[] { TenantUsers.TENANT_USERS.TENANT_ID }, Keys.TENANTS_PKEY, new TableField[] { Tenants.TENANTS.ID }, true);
}
