/*
 * This file is generated by jOOQ.
 */
package com.mayuran19.mms.jooq;


import com.mayuran19.mms.jooq.tables.PlatformUsers;
import com.mayuran19.mms.jooq.tables.SpringSession;
import com.mayuran19.mms.jooq.tables.SpringSessionAttributes;
import com.mayuran19.mms.jooq.tables.TenantUsers;
import com.mayuran19.mms.jooq.tables.Tenants;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.platform_users</code>.
     */
    public final PlatformUsers PLATFORM_USERS = PlatformUsers.PLATFORM_USERS;

    /**
     * The table <code>public.spring_session</code>.
     */
    public final SpringSession SPRING_SESSION = SpringSession.SPRING_SESSION;

    /**
     * The table <code>public.spring_session_attributes</code>.
     */
    public final SpringSessionAttributes SPRING_SESSION_ATTRIBUTES = SpringSessionAttributes.SPRING_SESSION_ATTRIBUTES;

    /**
     * The table <code>public.tenant_users</code>.
     */
    public final TenantUsers TENANT_USERS = TenantUsers.TENANT_USERS;

    /**
     * The table <code>public.tenants</code>.
     */
    public final Tenants TENANTS = Tenants.TENANTS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            PlatformUsers.PLATFORM_USERS,
            SpringSession.SPRING_SESSION,
            SpringSessionAttributes.SPRING_SESSION_ATTRIBUTES,
            TenantUsers.TENANT_USERS,
            Tenants.TENANTS
        );
    }
}
