/*
 * This file is generated by jOOQ.
 */
package com.mayuran19.mms.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TenantUsers implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID id;
    private UUID tenantId;
    private String email;
    private String passwordHash;
    private String firstName;
    private String lastName;
    private String status;
    private UUID createdBy;
    private OffsetDateTime createdDate;
    private UUID lastModifiedBy;
    private OffsetDateTime lastModifiedDate;

    public TenantUsers() {}

    public TenantUsers(TenantUsers value) {
        this.id = value.id;
        this.tenantId = value.tenantId;
        this.email = value.email;
        this.passwordHash = value.passwordHash;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
        this.status = value.status;
        this.createdBy = value.createdBy;
        this.createdDate = value.createdDate;
        this.lastModifiedBy = value.lastModifiedBy;
        this.lastModifiedDate = value.lastModifiedDate;
    }

    public TenantUsers(
        UUID id,
        UUID tenantId,
        String email,
        String passwordHash,
        String firstName,
        String lastName,
        String status,
        UUID createdBy,
        OffsetDateTime createdDate,
        UUID lastModifiedBy,
        OffsetDateTime lastModifiedDate
    ) {
        this.id = id;
        this.tenantId = tenantId;
        this.email = email;
        this.passwordHash = passwordHash;
        this.firstName = firstName;
        this.lastName = lastName;
        this.status = status;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedDate = lastModifiedDate;
    }

    /**
     * Getter for <code>public.tenant_users.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.tenant_users.id</code>.
     */
    public TenantUsers setId(UUID id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.tenant_users.tenant_id</code>.
     */
    public UUID getTenantId() {
        return this.tenantId;
    }

    /**
     * Setter for <code>public.tenant_users.tenant_id</code>.
     */
    public TenantUsers setTenantId(UUID tenantId) {
        this.tenantId = tenantId;
        return this;
    }

    /**
     * Getter for <code>public.tenant_users.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>public.tenant_users.email</code>.
     */
    public TenantUsers setEmail(String email) {
        this.email = email;
        return this;
    }

    /**
     * Getter for <code>public.tenant_users.password_hash</code>.
     */
    public String getPasswordHash() {
        return this.passwordHash;
    }

    /**
     * Setter for <code>public.tenant_users.password_hash</code>.
     */
    public TenantUsers setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
        return this;
    }

    /**
     * Getter for <code>public.tenant_users.first_name</code>.
     */
    public String getFirstName() {
        return this.firstName;
    }

    /**
     * Setter for <code>public.tenant_users.first_name</code>.
     */
    public TenantUsers setFirstName(String firstName) {
        this.firstName = firstName;
        return this;
    }

    /**
     * Getter for <code>public.tenant_users.last_name</code>.
     */
    public String getLastName() {
        return this.lastName;
    }

    /**
     * Setter for <code>public.tenant_users.last_name</code>.
     */
    public TenantUsers setLastName(String lastName) {
        this.lastName = lastName;
        return this;
    }

    /**
     * Getter for <code>public.tenant_users.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>public.tenant_users.status</code>.
     */
    public TenantUsers setStatus(String status) {
        this.status = status;
        return this;
    }

    /**
     * Getter for <code>public.tenant_users.created_by</code>.
     */
    public UUID getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>public.tenant_users.created_by</code>.
     */
    public TenantUsers setCreatedBy(UUID createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * Getter for <code>public.tenant_users.created_date</code>.
     */
    public OffsetDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Setter for <code>public.tenant_users.created_date</code>.
     */
    public TenantUsers setCreatedDate(OffsetDateTime createdDate) {
        this.createdDate = createdDate;
        return this;
    }

    /**
     * Getter for <code>public.tenant_users.last_modified_by</code>.
     */
    public UUID getLastModifiedBy() {
        return this.lastModifiedBy;
    }

    /**
     * Setter for <code>public.tenant_users.last_modified_by</code>.
     */
    public TenantUsers setLastModifiedBy(UUID lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
        return this;
    }

    /**
     * Getter for <code>public.tenant_users.last_modified_date</code>.
     */
    public OffsetDateTime getLastModifiedDate() {
        return this.lastModifiedDate;
    }

    /**
     * Setter for <code>public.tenant_users.last_modified_date</code>.
     */
    public TenantUsers setLastModifiedDate(OffsetDateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TenantUsers other = (TenantUsers) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.tenantId == null) {
            if (other.tenantId != null)
                return false;
        }
        else if (!this.tenantId.equals(other.tenantId))
            return false;
        if (this.email == null) {
            if (other.email != null)
                return false;
        }
        else if (!this.email.equals(other.email))
            return false;
        if (this.passwordHash == null) {
            if (other.passwordHash != null)
                return false;
        }
        else if (!this.passwordHash.equals(other.passwordHash))
            return false;
        if (this.firstName == null) {
            if (other.firstName != null)
                return false;
        }
        else if (!this.firstName.equals(other.firstName))
            return false;
        if (this.lastName == null) {
            if (other.lastName != null)
                return false;
        }
        else if (!this.lastName.equals(other.lastName))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.createdDate == null) {
            if (other.createdDate != null)
                return false;
        }
        else if (!this.createdDate.equals(other.createdDate))
            return false;
        if (this.lastModifiedBy == null) {
            if (other.lastModifiedBy != null)
                return false;
        }
        else if (!this.lastModifiedBy.equals(other.lastModifiedBy))
            return false;
        if (this.lastModifiedDate == null) {
            if (other.lastModifiedDate != null)
                return false;
        }
        else if (!this.lastModifiedDate.equals(other.lastModifiedDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.tenantId == null) ? 0 : this.tenantId.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.passwordHash == null) ? 0 : this.passwordHash.hashCode());
        result = prime * result + ((this.firstName == null) ? 0 : this.firstName.hashCode());
        result = prime * result + ((this.lastName == null) ? 0 : this.lastName.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.createdDate == null) ? 0 : this.createdDate.hashCode());
        result = prime * result + ((this.lastModifiedBy == null) ? 0 : this.lastModifiedBy.hashCode());
        result = prime * result + ((this.lastModifiedDate == null) ? 0 : this.lastModifiedDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TenantUsers (");

        sb.append(id);
        sb.append(", ").append(tenantId);
        sb.append(", ").append(email);
        sb.append(", ").append(passwordHash);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(status);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(lastModifiedBy);
        sb.append(", ").append(lastModifiedDate);

        sb.append(")");
        return sb.toString();
    }
}
