/*
 * This file is generated by jOOQ.
 */
package com.mayuran19.mms.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tenants implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID id;
    private String name;
    private String slug;
    private String status;
    private UUID createdBy;
    private OffsetDateTime createdDate;
    private UUID lastModifiedBy;
    private OffsetDateTime lastModifiedDate;

    public Tenants() {}

    public Tenants(Tenants value) {
        this.id = value.id;
        this.name = value.name;
        this.slug = value.slug;
        this.status = value.status;
        this.createdBy = value.createdBy;
        this.createdDate = value.createdDate;
        this.lastModifiedBy = value.lastModifiedBy;
        this.lastModifiedDate = value.lastModifiedDate;
    }

    public Tenants(
        UUID id,
        String name,
        String slug,
        String status,
        UUID createdBy,
        OffsetDateTime createdDate,
        UUID lastModifiedBy,
        OffsetDateTime lastModifiedDate
    ) {
        this.id = id;
        this.name = name;
        this.slug = slug;
        this.status = status;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedDate = lastModifiedDate;
    }

    /**
     * Getter for <code>public.tenants.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.tenants.id</code>.
     */
    public Tenants setId(UUID id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.tenants.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.tenants.name</code>.
     */
    public Tenants setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>public.tenants.slug</code>.
     */
    public String getSlug() {
        return this.slug;
    }

    /**
     * Setter for <code>public.tenants.slug</code>.
     */
    public Tenants setSlug(String slug) {
        this.slug = slug;
        return this;
    }

    /**
     * Getter for <code>public.tenants.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>public.tenants.status</code>.
     */
    public Tenants setStatus(String status) {
        this.status = status;
        return this;
    }

    /**
     * Getter for <code>public.tenants.created_by</code>.
     */
    public UUID getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>public.tenants.created_by</code>.
     */
    public Tenants setCreatedBy(UUID createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * Getter for <code>public.tenants.created_date</code>.
     */
    public OffsetDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Setter for <code>public.tenants.created_date</code>.
     */
    public Tenants setCreatedDate(OffsetDateTime createdDate) {
        this.createdDate = createdDate;
        return this;
    }

    /**
     * Getter for <code>public.tenants.last_modified_by</code>.
     */
    public UUID getLastModifiedBy() {
        return this.lastModifiedBy;
    }

    /**
     * Setter for <code>public.tenants.last_modified_by</code>.
     */
    public Tenants setLastModifiedBy(UUID lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
        return this;
    }

    /**
     * Getter for <code>public.tenants.last_modified_date</code>.
     */
    public OffsetDateTime getLastModifiedDate() {
        return this.lastModifiedDate;
    }

    /**
     * Setter for <code>public.tenants.last_modified_date</code>.
     */
    public Tenants setLastModifiedDate(OffsetDateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Tenants other = (Tenants) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.slug == null) {
            if (other.slug != null)
                return false;
        }
        else if (!this.slug.equals(other.slug))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.createdDate == null) {
            if (other.createdDate != null)
                return false;
        }
        else if (!this.createdDate.equals(other.createdDate))
            return false;
        if (this.lastModifiedBy == null) {
            if (other.lastModifiedBy != null)
                return false;
        }
        else if (!this.lastModifiedBy.equals(other.lastModifiedBy))
            return false;
        if (this.lastModifiedDate == null) {
            if (other.lastModifiedDate != null)
                return false;
        }
        else if (!this.lastModifiedDate.equals(other.lastModifiedDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.slug == null) ? 0 : this.slug.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.createdDate == null) ? 0 : this.createdDate.hashCode());
        result = prime * result + ((this.lastModifiedBy == null) ? 0 : this.lastModifiedBy.hashCode());
        result = prime * result + ((this.lastModifiedDate == null) ? 0 : this.lastModifiedDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Tenants (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(slug);
        sb.append(", ").append(status);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(lastModifiedBy);
        sb.append(", ").append(lastModifiedDate);

        sb.append(")");
        return sb.toString();
    }
}
