/*
 * This file is generated by jOOQ.
 */
package com.mayuran19.mms.jooq.tables;


import com.mayuran19.mms.jooq.Indexes;
import com.mayuran19.mms.jooq.Keys;
import com.mayuran19.mms.jooq.Public;
import com.mayuran19.mms.jooq.tables.records.PlatformUsersRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PlatformUsers extends TableImpl<PlatformUsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.platform_users</code>
     */
    public static final PlatformUsers PLATFORM_USERS = new PlatformUsers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PlatformUsersRecord> getRecordType() {
        return PlatformUsersRecord.class;
    }

    /**
     * The column <code>public.platform_users.id</code>.
     */
    public final TableField<PlatformUsersRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.platform_users.username</code>.
     */
    public final TableField<PlatformUsersRecord, String> USERNAME = createField(DSL.name("username"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.platform_users.email</code>.
     */
    public final TableField<PlatformUsersRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.platform_users.password_hash</code>.
     */
    public final TableField<PlatformUsersRecord, String> PASSWORD_HASH = createField(DSL.name("password_hash"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.platform_users.first_name</code>.
     */
    public final TableField<PlatformUsersRecord, String> FIRST_NAME = createField(DSL.name("first_name"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.platform_users.last_name</code>.
     */
    public final TableField<PlatformUsersRecord, String> LAST_NAME = createField(DSL.name("last_name"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.platform_users.is_active</code>.
     */
    public final TableField<PlatformUsersRecord, Boolean> IS_ACTIVE = createField(DSL.name("is_active"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.platform_users.is_email_verified</code>.
     */
    public final TableField<PlatformUsersRecord, Boolean> IS_EMAIL_VERIFIED = createField(DSL.name("is_email_verified"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.platform_users.created_by</code>.
     */
    public final TableField<PlatformUsersRecord, UUID> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.platform_users.created_date</code>.
     */
    public final TableField<PlatformUsersRecord, OffsetDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.platform_users.last_modified_by</code>.
     */
    public final TableField<PlatformUsersRecord, UUID> LAST_MODIFIED_BY = createField(DSL.name("last_modified_by"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.platform_users.last_modified_date</code>.
     */
    public final TableField<PlatformUsersRecord, OffsetDateTime> LAST_MODIFIED_DATE = createField(DSL.name("last_modified_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private PlatformUsers(Name alias, Table<PlatformUsersRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PlatformUsers(Name alias, Table<PlatformUsersRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.platform_users</code> table reference
     */
    public PlatformUsers(String alias) {
        this(DSL.name(alias), PLATFORM_USERS);
    }

    /**
     * Create an aliased <code>public.platform_users</code> table reference
     */
    public PlatformUsers(Name alias) {
        this(alias, PLATFORM_USERS);
    }

    /**
     * Create a <code>public.platform_users</code> table reference
     */
    public PlatformUsers() {
        this(DSL.name("platform_users"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_PLATFORM_USERS_EMAIL, Indexes.IDX_PLATFORM_USERS_IS_ACTIVE, Indexes.IDX_PLATFORM_USERS_USERNAME);
    }

    @Override
    public UniqueKey<PlatformUsersRecord> getPrimaryKey() {
        return Keys.PLATFORM_USERS_PKEY;
    }

    @Override
    public List<UniqueKey<PlatformUsersRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.PLATFORM_USERS_EMAIL_KEY, Keys.PLATFORM_USERS_USERNAME_KEY);
    }

    @Override
    public PlatformUsers as(String alias) {
        return new PlatformUsers(DSL.name(alias), this);
    }

    @Override
    public PlatformUsers as(Name alias) {
        return new PlatformUsers(alias, this);
    }

    @Override
    public PlatformUsers as(Table<?> alias) {
        return new PlatformUsers(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PlatformUsers rename(String name) {
        return new PlatformUsers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PlatformUsers rename(Name name) {
        return new PlatformUsers(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PlatformUsers rename(Table<?> name) {
        return new PlatformUsers(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlatformUsers where(Condition condition) {
        return new PlatformUsers(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlatformUsers where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlatformUsers where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlatformUsers where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlatformUsers where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlatformUsers where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlatformUsers where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlatformUsers where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlatformUsers whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlatformUsers whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
