/*
 * This file is generated by jOOQ.
 */
package com.mayuran19.mms.jooq.tables;


import com.mayuran19.mms.jooq.Indexes;
import com.mayuran19.mms.jooq.Keys;
import com.mayuran19.mms.jooq.Public;
import com.mayuran19.mms.jooq.tables.Tenants.TenantsPath;
import com.mayuran19.mms.jooq.tables.records.TenantUsersRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TenantUsers extends TableImpl<TenantUsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.tenant_users</code>
     */
    public static final TenantUsers TENANT_USERS = new TenantUsers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TenantUsersRecord> getRecordType() {
        return TenantUsersRecord.class;
    }

    /**
     * The column <code>public.tenant_users.id</code>.
     */
    public final TableField<TenantUsersRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.tenant_users.tenant_id</code>.
     */
    public final TableField<TenantUsersRecord, UUID> TENANT_ID = createField(DSL.name("tenant_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.tenant_users.email</code>.
     */
    public final TableField<TenantUsersRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.tenant_users.password_hash</code>.
     */
    public final TableField<TenantUsersRecord, String> PASSWORD_HASH = createField(DSL.name("password_hash"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.tenant_users.first_name</code>.
     */
    public final TableField<TenantUsersRecord, String> FIRST_NAME = createField(DSL.name("first_name"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.tenant_users.last_name</code>.
     */
    public final TableField<TenantUsersRecord, String> LAST_NAME = createField(DSL.name("last_name"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.tenant_users.status</code>.
     */
    public final TableField<TenantUsersRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.tenant_users.created_by</code>.
     */
    public final TableField<TenantUsersRecord, UUID> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.tenant_users.created_date</code>.
     */
    public final TableField<TenantUsersRecord, OffsetDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.tenant_users.last_modified_by</code>.
     */
    public final TableField<TenantUsersRecord, UUID> LAST_MODIFIED_BY = createField(DSL.name("last_modified_by"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.tenant_users.last_modified_date</code>.
     */
    public final TableField<TenantUsersRecord, OffsetDateTime> LAST_MODIFIED_DATE = createField(DSL.name("last_modified_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private TenantUsers(Name alias, Table<TenantUsersRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TenantUsers(Name alias, Table<TenantUsersRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.tenant_users</code> table reference
     */
    public TenantUsers(String alias) {
        this(DSL.name(alias), TENANT_USERS);
    }

    /**
     * Create an aliased <code>public.tenant_users</code> table reference
     */
    public TenantUsers(Name alias) {
        this(alias, TENANT_USERS);
    }

    /**
     * Create a <code>public.tenant_users</code> table reference
     */
    public TenantUsers() {
        this(DSL.name("tenant_users"), null);
    }

    public <O extends Record> TenantUsers(Table<O> path, ForeignKey<O, TenantUsersRecord> childPath, InverseForeignKey<O, TenantUsersRecord> parentPath) {
        super(path, childPath, parentPath, TENANT_USERS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TenantUsersPath extends TenantUsers implements Path<TenantUsersRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TenantUsersPath(Table<O> path, ForeignKey<O, TenantUsersRecord> childPath, InverseForeignKey<O, TenantUsersRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TenantUsersPath(Name alias, Table<TenantUsersRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TenantUsersPath as(String alias) {
            return new TenantUsersPath(DSL.name(alias), this);
        }

        @Override
        public TenantUsersPath as(Name alias) {
            return new TenantUsersPath(alias, this);
        }

        @Override
        public TenantUsersPath as(Table<?> alias) {
            return new TenantUsersPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_TENANT_USERS_EMAIL, Indexes.IDX_TENANT_USERS_STATUS, Indexes.IDX_TENANT_USERS_TENANT_ID);
    }

    @Override
    public UniqueKey<TenantUsersRecord> getPrimaryKey() {
        return Keys.TENANT_USERS_PKEY;
    }

    @Override
    public List<ForeignKey<TenantUsersRecord, ?>> getReferences() {
        return Arrays.asList(Keys.TENANT_USERS__FK_TENANT_USERS_TENANT_ID);
    }

    private transient TenantsPath _tenants;

    /**
     * Get the implicit join path to the <code>public.tenants</code> table.
     */
    public TenantsPath tenants() {
        if (_tenants == null)
            _tenants = new TenantsPath(this, Keys.TENANT_USERS__FK_TENANT_USERS_TENANT_ID, null);

        return _tenants;
    }

    @Override
    public TenantUsers as(String alias) {
        return new TenantUsers(DSL.name(alias), this);
    }

    @Override
    public TenantUsers as(Name alias) {
        return new TenantUsers(alias, this);
    }

    @Override
    public TenantUsers as(Table<?> alias) {
        return new TenantUsers(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TenantUsers rename(String name) {
        return new TenantUsers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TenantUsers rename(Name name) {
        return new TenantUsers(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TenantUsers rename(Table<?> name) {
        return new TenantUsers(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TenantUsers where(Condition condition) {
        return new TenantUsers(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TenantUsers where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TenantUsers where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TenantUsers where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TenantUsers where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TenantUsers where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TenantUsers where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TenantUsers where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TenantUsers whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TenantUsers whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
