/*
 * This file is generated by jOOQ.
 */
package com.mayuran19.mms.jooq.tables;


import com.mayuran19.mms.jooq.Indexes;
import com.mayuran19.mms.jooq.Keys;
import com.mayuran19.mms.jooq.Public;
import com.mayuran19.mms.jooq.tables.TenantUsers.TenantUsersPath;
import com.mayuran19.mms.jooq.tables.records.TenantsRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tenants extends TableImpl<TenantsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.tenants</code>
     */
    public static final Tenants TENANTS = new Tenants();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TenantsRecord> getRecordType() {
        return TenantsRecord.class;
    }

    /**
     * The column <code>public.tenants.id</code>.
     */
    public final TableField<TenantsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.tenants.name</code>.
     */
    public final TableField<TenantsRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.tenants.slug</code>.
     */
    public final TableField<TenantsRecord, String> SLUG = createField(DSL.name("slug"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.tenants.status</code>.
     */
    public final TableField<TenantsRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.tenants.created_by</code>.
     */
    public final TableField<TenantsRecord, UUID> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.tenants.created_date</code>.
     */
    public final TableField<TenantsRecord, OffsetDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.tenants.last_modified_by</code>.
     */
    public final TableField<TenantsRecord, UUID> LAST_MODIFIED_BY = createField(DSL.name("last_modified_by"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.tenants.last_modified_date</code>.
     */
    public final TableField<TenantsRecord, OffsetDateTime> LAST_MODIFIED_DATE = createField(DSL.name("last_modified_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private Tenants(Name alias, Table<TenantsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Tenants(Name alias, Table<TenantsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.tenants</code> table reference
     */
    public Tenants(String alias) {
        this(DSL.name(alias), TENANTS);
    }

    /**
     * Create an aliased <code>public.tenants</code> table reference
     */
    public Tenants(Name alias) {
        this(alias, TENANTS);
    }

    /**
     * Create a <code>public.tenants</code> table reference
     */
    public Tenants() {
        this(DSL.name("tenants"), null);
    }

    public <O extends Record> Tenants(Table<O> path, ForeignKey<O, TenantsRecord> childPath, InverseForeignKey<O, TenantsRecord> parentPath) {
        super(path, childPath, parentPath, TENANTS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TenantsPath extends Tenants implements Path<TenantsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TenantsPath(Table<O> path, ForeignKey<O, TenantsRecord> childPath, InverseForeignKey<O, TenantsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TenantsPath(Name alias, Table<TenantsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TenantsPath as(String alias) {
            return new TenantsPath(DSL.name(alias), this);
        }

        @Override
        public TenantsPath as(Name alias) {
            return new TenantsPath(alias, this);
        }

        @Override
        public TenantsPath as(Table<?> alias) {
            return new TenantsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_TENANTS_SLUG, Indexes.IDX_TENANTS_STATUS);
    }

    @Override
    public UniqueKey<TenantsRecord> getPrimaryKey() {
        return Keys.TENANTS_PKEY;
    }

    @Override
    public List<UniqueKey<TenantsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.TENANTS_SLUG_KEY);
    }

    private transient TenantUsersPath _tenantUsers;

    /**
     * Get the implicit to-many join path to the
     * <code>public.tenant_users</code> table
     */
    public TenantUsersPath tenantUsers() {
        if (_tenantUsers == null)
            _tenantUsers = new TenantUsersPath(this, null, Keys.TENANT_USERS__FK_TENANT_USERS_TENANT_ID.getInverseKey());

        return _tenantUsers;
    }

    @Override
    public Tenants as(String alias) {
        return new Tenants(DSL.name(alias), this);
    }

    @Override
    public Tenants as(Name alias) {
        return new Tenants(alias, this);
    }

    @Override
    public Tenants as(Table<?> alias) {
        return new Tenants(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Tenants rename(String name) {
        return new Tenants(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Tenants rename(Name name) {
        return new Tenants(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Tenants rename(Table<?> name) {
        return new Tenants(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Tenants where(Condition condition) {
        return new Tenants(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Tenants where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Tenants where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Tenants where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Tenants where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Tenants where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Tenants where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Tenants where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Tenants whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Tenants whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
