/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenantLoginRouteImport } from './routes/tenant/login'
import { Route as PlatformLoginRouteImport } from './routes/platform/login'
import { Route as PlatformDashboardRouteImport } from './routes/platform/dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantLoginRoute = TenantLoginRouteImport.update({
  id: '/tenant/login',
  path: '/tenant/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformLoginRoute = PlatformLoginRouteImport.update({
  id: '/platform/login',
  path: '/platform/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformDashboardRoute = PlatformDashboardRouteImport.update({
  id: '/platform/dashboard',
  path: '/platform/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/platform/dashboard': typeof PlatformDashboardRoute
  '/platform/login': typeof PlatformLoginRoute
  '/tenant/login': typeof TenantLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/platform/dashboard': typeof PlatformDashboardRoute
  '/platform/login': typeof PlatformLoginRoute
  '/tenant/login': typeof TenantLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/platform/dashboard': typeof PlatformDashboardRoute
  '/platform/login': typeof PlatformLoginRoute
  '/tenant/login': typeof TenantLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/platform/dashboard' | '/platform/login' | '/tenant/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/platform/dashboard' | '/platform/login' | '/tenant/login'
  id:
    | '__root__'
    | '/'
    | '/platform/dashboard'
    | '/platform/login'
    | '/tenant/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlatformDashboardRoute: typeof PlatformDashboardRoute
  PlatformLoginRoute: typeof PlatformLoginRoute
  TenantLoginRoute: typeof TenantLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/login': {
      id: '/tenant/login'
      path: '/tenant/login'
      fullPath: '/tenant/login'
      preLoaderRoute: typeof TenantLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/login': {
      id: '/platform/login'
      path: '/platform/login'
      fullPath: '/platform/login'
      preLoaderRoute: typeof PlatformLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/dashboard': {
      id: '/platform/dashboard'
      path: '/platform/dashboard'
      fullPath: '/platform/dashboard'
      preLoaderRoute: typeof PlatformDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlatformDashboardRoute: PlatformDashboardRoute,
  PlatformLoginRoute: PlatformLoginRoute,
  TenantLoginRoute: TenantLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
