/*
 * This file is generated by jOOQ.
 */
package com.mayuran19.mms.jooq.tables.daos;


import com.mayuran19.mms.jooq.tables.PlatformUsers;
import com.mayuran19.mms.jooq.tables.records.PlatformUsersRecord;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PlatformUsersDao extends DAOImpl<PlatformUsersRecord, com.mayuran19.mms.jooq.tables.pojos.PlatformUsers, UUID> {

    /**
     * Create a new PlatformUsersDao without any configuration
     */
    public PlatformUsersDao() {
        super(PlatformUsers.PLATFORM_USERS, com.mayuran19.mms.jooq.tables.pojos.PlatformUsers.class);
    }

    /**
     * Create a new PlatformUsersDao with an attached configuration
     */
    public PlatformUsersDao(Configuration configuration) {
        super(PlatformUsers.PLATFORM_USERS, com.mayuran19.mms.jooq.tables.pojos.PlatformUsers.class, configuration);
    }

    @Override
    public UUID getId(com.mayuran19.mms.jooq.tables.pojos.PlatformUsers object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.PlatformUsers> fetchRangeOfId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(PlatformUsers.PLATFORM_USERS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.PlatformUsers> fetchById(UUID... values) {
        return fetch(PlatformUsers.PLATFORM_USERS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.mayuran19.mms.jooq.tables.pojos.PlatformUsers fetchOneById(UUID value) {
        return fetchOne(PlatformUsers.PLATFORM_USERS.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.mayuran19.mms.jooq.tables.pojos.PlatformUsers> fetchOptionalById(UUID value) {
        return fetchOptional(PlatformUsers.PLATFORM_USERS.ID, value);
    }

    /**
     * Fetch records that have <code>username BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.PlatformUsers> fetchRangeOfUsername(String lowerInclusive, String upperInclusive) {
        return fetchRange(PlatformUsers.PLATFORM_USERS.USERNAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>username IN (values)</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.PlatformUsers> fetchByUsername(String... values) {
        return fetch(PlatformUsers.PLATFORM_USERS.USERNAME, values);
    }

    /**
     * Fetch a unique record that has <code>username = value</code>
     */
    public com.mayuran19.mms.jooq.tables.pojos.PlatformUsers fetchOneByUsername(String value) {
        return fetchOne(PlatformUsers.PLATFORM_USERS.USERNAME, value);
    }

    /**
     * Fetch a unique record that has <code>username = value</code>
     */
    public Optional<com.mayuran19.mms.jooq.tables.pojos.PlatformUsers> fetchOptionalByUsername(String value) {
        return fetchOptional(PlatformUsers.PLATFORM_USERS.USERNAME, value);
    }

    /**
     * Fetch records that have <code>email BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.PlatformUsers> fetchRangeOfEmail(String lowerInclusive, String upperInclusive) {
        return fetchRange(PlatformUsers.PLATFORM_USERS.EMAIL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.PlatformUsers> fetchByEmail(String... values) {
        return fetch(PlatformUsers.PLATFORM_USERS.EMAIL, values);
    }

    /**
     * Fetch a unique record that has <code>email = value</code>
     */
    public com.mayuran19.mms.jooq.tables.pojos.PlatformUsers fetchOneByEmail(String value) {
        return fetchOne(PlatformUsers.PLATFORM_USERS.EMAIL, value);
    }

    /**
     * Fetch a unique record that has <code>email = value</code>
     */
    public Optional<com.mayuran19.mms.jooq.tables.pojos.PlatformUsers> fetchOptionalByEmail(String value) {
        return fetchOptional(PlatformUsers.PLATFORM_USERS.EMAIL, value);
    }

    /**
     * Fetch records that have <code>password_hash BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.PlatformUsers> fetchRangeOfPasswordHash(String lowerInclusive, String upperInclusive) {
        return fetchRange(PlatformUsers.PLATFORM_USERS.PASSWORD_HASH, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>password_hash IN (values)</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.PlatformUsers> fetchByPasswordHash(String... values) {
        return fetch(PlatformUsers.PLATFORM_USERS.PASSWORD_HASH, values);
    }

    /**
     * Fetch records that have <code>first_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.PlatformUsers> fetchRangeOfFirstName(String lowerInclusive, String upperInclusive) {
        return fetchRange(PlatformUsers.PLATFORM_USERS.FIRST_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>first_name IN (values)</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.PlatformUsers> fetchByFirstName(String... values) {
        return fetch(PlatformUsers.PLATFORM_USERS.FIRST_NAME, values);
    }

    /**
     * Fetch records that have <code>last_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.PlatformUsers> fetchRangeOfLastName(String lowerInclusive, String upperInclusive) {
        return fetchRange(PlatformUsers.PLATFORM_USERS.LAST_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_name IN (values)</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.PlatformUsers> fetchByLastName(String... values) {
        return fetch(PlatformUsers.PLATFORM_USERS.LAST_NAME, values);
    }

    /**
     * Fetch records that have <code>is_active BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.PlatformUsers> fetchRangeOfIsActive(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(PlatformUsers.PLATFORM_USERS.IS_ACTIVE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>is_active IN (values)</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.PlatformUsers> fetchByIsActive(Boolean... values) {
        return fetch(PlatformUsers.PLATFORM_USERS.IS_ACTIVE, values);
    }

    /**
     * Fetch records that have <code>is_email_verified BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.PlatformUsers> fetchRangeOfIsEmailVerified(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(PlatformUsers.PLATFORM_USERS.IS_EMAIL_VERIFIED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>is_email_verified IN (values)</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.PlatformUsers> fetchByIsEmailVerified(Boolean... values) {
        return fetch(PlatformUsers.PLATFORM_USERS.IS_EMAIL_VERIFIED, values);
    }

    /**
     * Fetch records that have <code>created_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.PlatformUsers> fetchRangeOfCreatedBy(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(PlatformUsers.PLATFORM_USERS.CREATED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_by IN (values)</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.PlatformUsers> fetchByCreatedBy(UUID... values) {
        return fetch(PlatformUsers.PLATFORM_USERS.CREATED_BY, values);
    }

    /**
     * Fetch records that have <code>created_date BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.PlatformUsers> fetchRangeOfCreatedDate(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(PlatformUsers.PLATFORM_USERS.CREATED_DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_date IN (values)</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.PlatformUsers> fetchByCreatedDate(OffsetDateTime... values) {
        return fetch(PlatformUsers.PLATFORM_USERS.CREATED_DATE, values);
    }

    /**
     * Fetch records that have <code>last_modified_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.PlatformUsers> fetchRangeOfLastModifiedBy(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(PlatformUsers.PLATFORM_USERS.LAST_MODIFIED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_modified_by IN (values)</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.PlatformUsers> fetchByLastModifiedBy(UUID... values) {
        return fetch(PlatformUsers.PLATFORM_USERS.LAST_MODIFIED_BY, values);
    }

    /**
     * Fetch records that have <code>last_modified_date BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.PlatformUsers> fetchRangeOfLastModifiedDate(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(PlatformUsers.PLATFORM_USERS.LAST_MODIFIED_DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_modified_date IN (values)</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.PlatformUsers> fetchByLastModifiedDate(OffsetDateTime... values) {
        return fetch(PlatformUsers.PLATFORM_USERS.LAST_MODIFIED_DATE, values);
    }
}
