/*
 * This file is generated by jOOQ.
 */
package com.mayuran19.mms.jooq.tables.daos;


import com.mayuran19.mms.jooq.tables.SpringSession;
import com.mayuran19.mms.jooq.tables.records.SpringSessionRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SpringSessionDao extends DAOImpl<SpringSessionRecord, com.mayuran19.mms.jooq.tables.pojos.SpringSession, String> {

    /**
     * Create a new SpringSessionDao without any configuration
     */
    public SpringSessionDao() {
        super(SpringSession.SPRING_SESSION, com.mayuran19.mms.jooq.tables.pojos.SpringSession.class);
    }

    /**
     * Create a new SpringSessionDao with an attached configuration
     */
    public SpringSessionDao(Configuration configuration) {
        super(SpringSession.SPRING_SESSION, com.mayuran19.mms.jooq.tables.pojos.SpringSession.class, configuration);
    }

    @Override
    public String getId(com.mayuran19.mms.jooq.tables.pojos.SpringSession object) {
        return object.getPrimaryId();
    }

    /**
     * Fetch records that have <code>primary_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.SpringSession> fetchRangeOfPrimaryId(String lowerInclusive, String upperInclusive) {
        return fetchRange(SpringSession.SPRING_SESSION.PRIMARY_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>primary_id IN (values)</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.SpringSession> fetchByPrimaryId(String... values) {
        return fetch(SpringSession.SPRING_SESSION.PRIMARY_ID, values);
    }

    /**
     * Fetch a unique record that has <code>primary_id = value</code>
     */
    public com.mayuran19.mms.jooq.tables.pojos.SpringSession fetchOneByPrimaryId(String value) {
        return fetchOne(SpringSession.SPRING_SESSION.PRIMARY_ID, value);
    }

    /**
     * Fetch a unique record that has <code>primary_id = value</code>
     */
    public Optional<com.mayuran19.mms.jooq.tables.pojos.SpringSession> fetchOptionalByPrimaryId(String value) {
        return fetchOptional(SpringSession.SPRING_SESSION.PRIMARY_ID, value);
    }

    /**
     * Fetch records that have <code>session_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.SpringSession> fetchRangeOfSessionId(String lowerInclusive, String upperInclusive) {
        return fetchRange(SpringSession.SPRING_SESSION.SESSION_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>session_id IN (values)</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.SpringSession> fetchBySessionId(String... values) {
        return fetch(SpringSession.SPRING_SESSION.SESSION_ID, values);
    }

    /**
     * Fetch a unique record that has <code>session_id = value</code>
     */
    public com.mayuran19.mms.jooq.tables.pojos.SpringSession fetchOneBySessionId(String value) {
        return fetchOne(SpringSession.SPRING_SESSION.SESSION_ID, value);
    }

    /**
     * Fetch a unique record that has <code>session_id = value</code>
     */
    public Optional<com.mayuran19.mms.jooq.tables.pojos.SpringSession> fetchOptionalBySessionId(String value) {
        return fetchOptional(SpringSession.SPRING_SESSION.SESSION_ID, value);
    }

    /**
     * Fetch records that have <code>creation_time BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.SpringSession> fetchRangeOfCreationTime(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(SpringSession.SPRING_SESSION.CREATION_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>creation_time IN (values)</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.SpringSession> fetchByCreationTime(Long... values) {
        return fetch(SpringSession.SPRING_SESSION.CREATION_TIME, values);
    }

    /**
     * Fetch records that have <code>last_access_time BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.SpringSession> fetchRangeOfLastAccessTime(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(SpringSession.SPRING_SESSION.LAST_ACCESS_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_access_time IN (values)</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.SpringSession> fetchByLastAccessTime(Long... values) {
        return fetch(SpringSession.SPRING_SESSION.LAST_ACCESS_TIME, values);
    }

    /**
     * Fetch records that have <code>max_inactive_interval BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.SpringSession> fetchRangeOfMaxInactiveInterval(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(SpringSession.SPRING_SESSION.MAX_INACTIVE_INTERVAL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>max_inactive_interval IN (values)</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.SpringSession> fetchByMaxInactiveInterval(Integer... values) {
        return fetch(SpringSession.SPRING_SESSION.MAX_INACTIVE_INTERVAL, values);
    }

    /**
     * Fetch records that have <code>expiry_time BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.SpringSession> fetchRangeOfExpiryTime(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(SpringSession.SPRING_SESSION.EXPIRY_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>expiry_time IN (values)</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.SpringSession> fetchByExpiryTime(Long... values) {
        return fetch(SpringSession.SPRING_SESSION.EXPIRY_TIME, values);
    }

    /**
     * Fetch records that have <code>principal_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.SpringSession> fetchRangeOfPrincipalName(String lowerInclusive, String upperInclusive) {
        return fetchRange(SpringSession.SPRING_SESSION.PRINCIPAL_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>principal_name IN (values)</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.SpringSession> fetchByPrincipalName(String... values) {
        return fetch(SpringSession.SPRING_SESSION.PRINCIPAL_NAME, values);
    }
}
