/*
 * This file is generated by jOOQ.
 */
package com.mayuran19.mms.jooq.tables.daos;


import com.mayuran19.mms.jooq.tables.SpringSessionAttributes;
import com.mayuran19.mms.jooq.tables.records.SpringSessionAttributesRecord;

import java.util.List;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SpringSessionAttributesDao extends DAOImpl<SpringSessionAttributesRecord, com.mayuran19.mms.jooq.tables.pojos.SpringSessionAttributes, Record2<String, String>> {

    /**
     * Create a new SpringSessionAttributesDao without any configuration
     */
    public SpringSessionAttributesDao() {
        super(SpringSessionAttributes.SPRING_SESSION_ATTRIBUTES, com.mayuran19.mms.jooq.tables.pojos.SpringSessionAttributes.class);
    }

    /**
     * Create a new SpringSessionAttributesDao with an attached configuration
     */
    public SpringSessionAttributesDao(Configuration configuration) {
        super(SpringSessionAttributes.SPRING_SESSION_ATTRIBUTES, com.mayuran19.mms.jooq.tables.pojos.SpringSessionAttributes.class, configuration);
    }

    @Override
    public Record2<String, String> getId(com.mayuran19.mms.jooq.tables.pojos.SpringSessionAttributes object) {
        return compositeKeyRecord(object.getSessionPrimaryId(), object.getAttributeName());
    }

    /**
     * Fetch records that have <code>session_primary_id BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.SpringSessionAttributes> fetchRangeOfSessionPrimaryId(String lowerInclusive, String upperInclusive) {
        return fetchRange(SpringSessionAttributes.SPRING_SESSION_ATTRIBUTES.SESSION_PRIMARY_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>session_primary_id IN (values)</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.SpringSessionAttributes> fetchBySessionPrimaryId(String... values) {
        return fetch(SpringSessionAttributes.SPRING_SESSION_ATTRIBUTES.SESSION_PRIMARY_ID, values);
    }

    /**
     * Fetch records that have <code>attribute_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.SpringSessionAttributes> fetchRangeOfAttributeName(String lowerInclusive, String upperInclusive) {
        return fetchRange(SpringSessionAttributes.SPRING_SESSION_ATTRIBUTES.ATTRIBUTE_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>attribute_name IN (values)</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.SpringSessionAttributes> fetchByAttributeName(String... values) {
        return fetch(SpringSessionAttributes.SPRING_SESSION_ATTRIBUTES.ATTRIBUTE_NAME, values);
    }

    /**
     * Fetch records that have <code>attribute_bytes BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.SpringSessionAttributes> fetchRangeOfAttributeBytes(byte[] lowerInclusive, byte[] upperInclusive) {
        return fetchRange(SpringSessionAttributes.SPRING_SESSION_ATTRIBUTES.ATTRIBUTE_BYTES, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>attribute_bytes IN (values)</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.SpringSessionAttributes> fetchByAttributeBytes(byte[]... values) {
        return fetch(SpringSessionAttributes.SPRING_SESSION_ATTRIBUTES.ATTRIBUTE_BYTES, values);
    }
}
