/*
 * This file is generated by jOOQ.
 */
package com.mayuran19.mms.jooq.tables.daos;


import com.mayuran19.mms.jooq.tables.Tenants;
import com.mayuran19.mms.jooq.tables.records.TenantsRecord;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TenantsDao extends DAOImpl<TenantsRecord, com.mayuran19.mms.jooq.tables.pojos.Tenants, UUID> {

    /**
     * Create a new TenantsDao without any configuration
     */
    public TenantsDao() {
        super(Tenants.TENANTS, com.mayuran19.mms.jooq.tables.pojos.Tenants.class);
    }

    /**
     * Create a new TenantsDao with an attached configuration
     */
    public TenantsDao(Configuration configuration) {
        super(Tenants.TENANTS, com.mayuran19.mms.jooq.tables.pojos.Tenants.class, configuration);
    }

    @Override
    public UUID getId(com.mayuran19.mms.jooq.tables.pojos.Tenants object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.Tenants> fetchRangeOfId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(Tenants.TENANTS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.Tenants> fetchById(UUID... values) {
        return fetch(Tenants.TENANTS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.mayuran19.mms.jooq.tables.pojos.Tenants fetchOneById(UUID value) {
        return fetchOne(Tenants.TENANTS.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.mayuran19.mms.jooq.tables.pojos.Tenants> fetchOptionalById(UUID value) {
        return fetchOptional(Tenants.TENANTS.ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.Tenants> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Tenants.TENANTS.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.Tenants> fetchByName(String... values) {
        return fetch(Tenants.TENANTS.NAME, values);
    }

    /**
     * Fetch records that have <code>slug BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.Tenants> fetchRangeOfSlug(String lowerInclusive, String upperInclusive) {
        return fetchRange(Tenants.TENANTS.SLUG, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>slug IN (values)</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.Tenants> fetchBySlug(String... values) {
        return fetch(Tenants.TENANTS.SLUG, values);
    }

    /**
     * Fetch a unique record that has <code>slug = value</code>
     */
    public com.mayuran19.mms.jooq.tables.pojos.Tenants fetchOneBySlug(String value) {
        return fetchOne(Tenants.TENANTS.SLUG, value);
    }

    /**
     * Fetch a unique record that has <code>slug = value</code>
     */
    public Optional<com.mayuran19.mms.jooq.tables.pojos.Tenants> fetchOptionalBySlug(String value) {
        return fetchOptional(Tenants.TENANTS.SLUG, value);
    }

    /**
     * Fetch records that have <code>status BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.Tenants> fetchRangeOfStatus(String lowerInclusive, String upperInclusive) {
        return fetchRange(Tenants.TENANTS.STATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.Tenants> fetchByStatus(String... values) {
        return fetch(Tenants.TENANTS.STATUS, values);
    }

    /**
     * Fetch records that have <code>created_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.Tenants> fetchRangeOfCreatedBy(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(Tenants.TENANTS.CREATED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_by IN (values)</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.Tenants> fetchByCreatedBy(UUID... values) {
        return fetch(Tenants.TENANTS.CREATED_BY, values);
    }

    /**
     * Fetch records that have <code>created_date BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.Tenants> fetchRangeOfCreatedDate(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(Tenants.TENANTS.CREATED_DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_date IN (values)</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.Tenants> fetchByCreatedDate(OffsetDateTime... values) {
        return fetch(Tenants.TENANTS.CREATED_DATE, values);
    }

    /**
     * Fetch records that have <code>last_modified_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.Tenants> fetchRangeOfLastModifiedBy(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(Tenants.TENANTS.LAST_MODIFIED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_modified_by IN (values)</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.Tenants> fetchByLastModifiedBy(UUID... values) {
        return fetch(Tenants.TENANTS.LAST_MODIFIED_BY, values);
    }

    /**
     * Fetch records that have <code>last_modified_date BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.Tenants> fetchRangeOfLastModifiedDate(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(Tenants.TENANTS.LAST_MODIFIED_DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_modified_date IN (values)</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.Tenants> fetchByLastModifiedDate(OffsetDateTime... values) {
        return fetch(Tenants.TENANTS.LAST_MODIFIED_DATE, values);
    }
}
