/*
 * This file is generated by jOOQ.
 */
package com.mayuran19.mms.jooq.tables.daos;


import com.mayuran19.mms.jooq.tables.TenantUsers;
import com.mayuran19.mms.jooq.tables.records.TenantUsersRecord;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TenantUsersDao extends DAOImpl<TenantUsersRecord, com.mayuran19.mms.jooq.tables.pojos.TenantUsers, UUID> {

    /**
     * Create a new TenantUsersDao without any configuration
     */
    public TenantUsersDao() {
        super(TenantUsers.TENANT_USERS, com.mayuran19.mms.jooq.tables.pojos.TenantUsers.class);
    }

    /**
     * Create a new TenantUsersDao with an attached configuration
     */
    public TenantUsersDao(Configuration configuration) {
        super(TenantUsers.TENANT_USERS, com.mayuran19.mms.jooq.tables.pojos.TenantUsers.class, configuration);
    }

    @Override
    public UUID getId(com.mayuran19.mms.jooq.tables.pojos.TenantUsers object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.TenantUsers> fetchRangeOfId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(TenantUsers.TENANT_USERS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.TenantUsers> fetchById(UUID... values) {
        return fetch(TenantUsers.TENANT_USERS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.mayuran19.mms.jooq.tables.pojos.TenantUsers fetchOneById(UUID value) {
        return fetchOne(TenantUsers.TENANT_USERS.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.mayuran19.mms.jooq.tables.pojos.TenantUsers> fetchOptionalById(UUID value) {
        return fetchOptional(TenantUsers.TENANT_USERS.ID, value);
    }

    /**
     * Fetch records that have <code>tenant_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.TenantUsers> fetchRangeOfTenantId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(TenantUsers.TENANT_USERS.TENANT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>tenant_id IN (values)</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.TenantUsers> fetchByTenantId(UUID... values) {
        return fetch(TenantUsers.TENANT_USERS.TENANT_ID, values);
    }

    /**
     * Fetch records that have <code>email BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.TenantUsers> fetchRangeOfEmail(String lowerInclusive, String upperInclusive) {
        return fetchRange(TenantUsers.TENANT_USERS.EMAIL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.TenantUsers> fetchByEmail(String... values) {
        return fetch(TenantUsers.TENANT_USERS.EMAIL, values);
    }

    /**
     * Fetch records that have <code>password_hash BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.TenantUsers> fetchRangeOfPasswordHash(String lowerInclusive, String upperInclusive) {
        return fetchRange(TenantUsers.TENANT_USERS.PASSWORD_HASH, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>password_hash IN (values)</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.TenantUsers> fetchByPasswordHash(String... values) {
        return fetch(TenantUsers.TENANT_USERS.PASSWORD_HASH, values);
    }

    /**
     * Fetch records that have <code>first_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.TenantUsers> fetchRangeOfFirstName(String lowerInclusive, String upperInclusive) {
        return fetchRange(TenantUsers.TENANT_USERS.FIRST_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>first_name IN (values)</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.TenantUsers> fetchByFirstName(String... values) {
        return fetch(TenantUsers.TENANT_USERS.FIRST_NAME, values);
    }

    /**
     * Fetch records that have <code>last_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.TenantUsers> fetchRangeOfLastName(String lowerInclusive, String upperInclusive) {
        return fetchRange(TenantUsers.TENANT_USERS.LAST_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_name IN (values)</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.TenantUsers> fetchByLastName(String... values) {
        return fetch(TenantUsers.TENANT_USERS.LAST_NAME, values);
    }

    /**
     * Fetch records that have <code>status BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.TenantUsers> fetchRangeOfStatus(String lowerInclusive, String upperInclusive) {
        return fetchRange(TenantUsers.TENANT_USERS.STATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.TenantUsers> fetchByStatus(String... values) {
        return fetch(TenantUsers.TENANT_USERS.STATUS, values);
    }

    /**
     * Fetch records that have <code>created_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.TenantUsers> fetchRangeOfCreatedBy(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(TenantUsers.TENANT_USERS.CREATED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_by IN (values)</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.TenantUsers> fetchByCreatedBy(UUID... values) {
        return fetch(TenantUsers.TENANT_USERS.CREATED_BY, values);
    }

    /**
     * Fetch records that have <code>created_date BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.TenantUsers> fetchRangeOfCreatedDate(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(TenantUsers.TENANT_USERS.CREATED_DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_date IN (values)</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.TenantUsers> fetchByCreatedDate(OffsetDateTime... values) {
        return fetch(TenantUsers.TENANT_USERS.CREATED_DATE, values);
    }

    /**
     * Fetch records that have <code>last_modified_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.TenantUsers> fetchRangeOfLastModifiedBy(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(TenantUsers.TENANT_USERS.LAST_MODIFIED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_modified_by IN (values)</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.TenantUsers> fetchByLastModifiedBy(UUID... values) {
        return fetch(TenantUsers.TENANT_USERS.LAST_MODIFIED_BY, values);
    }

    /**
     * Fetch records that have <code>last_modified_date BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.TenantUsers> fetchRangeOfLastModifiedDate(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(TenantUsers.TENANT_USERS.LAST_MODIFIED_DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_modified_date IN (values)</code>
     */
    public List<com.mayuran19.mms.jooq.tables.pojos.TenantUsers> fetchByLastModifiedDate(OffsetDateTime... values) {
        return fetch(TenantUsers.TENANT_USERS.LAST_MODIFIED_DATE, values);
    }
}
