/*
 * This file is generated by jOOQ.
 */
package com.mayuran19.mms.jooq.tables.records;


import com.mayuran19.mms.jooq.tables.PlatformUsers;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PlatformUsersRecord extends UpdatableRecordImpl<PlatformUsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.platform_users.id</code>.
     */
    public PlatformUsersRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.platform_users.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.platform_users.username</code>.
     */
    public PlatformUsersRecord setUsername(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.platform_users.username</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.platform_users.email</code>.
     */
    public PlatformUsersRecord setEmail(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.platform_users.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.platform_users.password_hash</code>.
     */
    public PlatformUsersRecord setPasswordHash(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.platform_users.password_hash</code>.
     */
    public String getPasswordHash() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.platform_users.first_name</code>.
     */
    public PlatformUsersRecord setFirstName(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.platform_users.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.platform_users.last_name</code>.
     */
    public PlatformUsersRecord setLastName(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.platform_users.last_name</code>.
     */
    public String getLastName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.platform_users.is_active</code>.
     */
    public PlatformUsersRecord setIsActive(Boolean value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.platform_users.is_active</code>.
     */
    public Boolean getIsActive() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>public.platform_users.is_email_verified</code>.
     */
    public PlatformUsersRecord setIsEmailVerified(Boolean value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.platform_users.is_email_verified</code>.
     */
    public Boolean getIsEmailVerified() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>public.platform_users.created_by</code>.
     */
    public PlatformUsersRecord setCreatedBy(UUID value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.platform_users.created_by</code>.
     */
    public UUID getCreatedBy() {
        return (UUID) get(8);
    }

    /**
     * Setter for <code>public.platform_users.created_date</code>.
     */
    public PlatformUsersRecord setCreatedDate(OffsetDateTime value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.platform_users.created_date</code>.
     */
    public OffsetDateTime getCreatedDate() {
        return (OffsetDateTime) get(9);
    }

    /**
     * Setter for <code>public.platform_users.last_modified_by</code>.
     */
    public PlatformUsersRecord setLastModifiedBy(UUID value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.platform_users.last_modified_by</code>.
     */
    public UUID getLastModifiedBy() {
        return (UUID) get(10);
    }

    /**
     * Setter for <code>public.platform_users.last_modified_date</code>.
     */
    public PlatformUsersRecord setLastModifiedDate(OffsetDateTime value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.platform_users.last_modified_date</code>.
     */
    public OffsetDateTime getLastModifiedDate() {
        return (OffsetDateTime) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlatformUsersRecord
     */
    public PlatformUsersRecord() {
        super(PlatformUsers.PLATFORM_USERS);
    }

    /**
     * Create a detached, initialised PlatformUsersRecord
     */
    public PlatformUsersRecord(UUID id, String username, String email, String passwordHash, String firstName, String lastName, Boolean isActive, Boolean isEmailVerified, UUID createdBy, OffsetDateTime createdDate, UUID lastModifiedBy, OffsetDateTime lastModifiedDate) {
        super(PlatformUsers.PLATFORM_USERS);

        setId(id);
        setUsername(username);
        setEmail(email);
        setPasswordHash(passwordHash);
        setFirstName(firstName);
        setLastName(lastName);
        setIsActive(isActive);
        setIsEmailVerified(isEmailVerified);
        setCreatedBy(createdBy);
        setCreatedDate(createdDate);
        setLastModifiedBy(lastModifiedBy);
        setLastModifiedDate(lastModifiedDate);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised PlatformUsersRecord
     */
    public PlatformUsersRecord(com.mayuran19.mms.jooq.tables.pojos.PlatformUsers value) {
        super(PlatformUsers.PLATFORM_USERS);

        if (value != null) {
            setId(value.getId());
            setUsername(value.getUsername());
            setEmail(value.getEmail());
            setPasswordHash(value.getPasswordHash());
            setFirstName(value.getFirstName());
            setLastName(value.getLastName());
            setIsActive(value.getIsActive());
            setIsEmailVerified(value.getIsEmailVerified());
            setCreatedBy(value.getCreatedBy());
            setCreatedDate(value.getCreatedDate());
            setLastModifiedBy(value.getLastModifiedBy());
            setLastModifiedDate(value.getLastModifiedDate());
            resetChangedOnNotNull();
        }
    }
}
