/*
 * This file is generated by jOOQ.
 */
package com.mayuran19.mms.jooq.tables.records;


import com.mayuran19.mms.jooq.tables.SpringSession;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SpringSessionRecord extends UpdatableRecordImpl<SpringSessionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.spring_session.primary_id</code>.
     */
    public SpringSessionRecord setPrimaryId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.spring_session.primary_id</code>.
     */
    public String getPrimaryId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.spring_session.session_id</code>.
     */
    public SpringSessionRecord setSessionId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.spring_session.session_id</code>.
     */
    public String getSessionId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.spring_session.creation_time</code>.
     */
    public SpringSessionRecord setCreationTime(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.spring_session.creation_time</code>.
     */
    public Long getCreationTime() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.spring_session.last_access_time</code>.
     */
    public SpringSessionRecord setLastAccessTime(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.spring_session.last_access_time</code>.
     */
    public Long getLastAccessTime() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.spring_session.max_inactive_interval</code>.
     */
    public SpringSessionRecord setMaxInactiveInterval(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.spring_session.max_inactive_interval</code>.
     */
    public Integer getMaxInactiveInterval() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.spring_session.expiry_time</code>.
     */
    public SpringSessionRecord setExpiryTime(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.spring_session.expiry_time</code>.
     */
    public Long getExpiryTime() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.spring_session.principal_name</code>.
     */
    public SpringSessionRecord setPrincipalName(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.spring_session.principal_name</code>.
     */
    public String getPrincipalName() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpringSessionRecord
     */
    public SpringSessionRecord() {
        super(SpringSession.SPRING_SESSION);
    }

    /**
     * Create a detached, initialised SpringSessionRecord
     */
    public SpringSessionRecord(String primaryId, String sessionId, Long creationTime, Long lastAccessTime, Integer maxInactiveInterval, Long expiryTime, String principalName) {
        super(SpringSession.SPRING_SESSION);

        setPrimaryId(primaryId);
        setSessionId(sessionId);
        setCreationTime(creationTime);
        setLastAccessTime(lastAccessTime);
        setMaxInactiveInterval(maxInactiveInterval);
        setExpiryTime(expiryTime);
        setPrincipalName(principalName);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised SpringSessionRecord
     */
    public SpringSessionRecord(com.mayuran19.mms.jooq.tables.pojos.SpringSession value) {
        super(SpringSession.SPRING_SESSION);

        if (value != null) {
            setPrimaryId(value.getPrimaryId());
            setSessionId(value.getSessionId());
            setCreationTime(value.getCreationTime());
            setLastAccessTime(value.getLastAccessTime());
            setMaxInactiveInterval(value.getMaxInactiveInterval());
            setExpiryTime(value.getExpiryTime());
            setPrincipalName(value.getPrincipalName());
            resetChangedOnNotNull();
        }
    }
}
