/*
 * This file is generated by jOOQ.
 */
package com.mayuran19.mms.jooq.tables.records;


import com.mayuran19.mms.jooq.tables.Tenants;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TenantsRecord extends UpdatableRecordImpl<TenantsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.tenants.id</code>.
     */
    public TenantsRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.tenants.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.tenants.name</code>.
     */
    public TenantsRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.tenants.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.tenants.slug</code>.
     */
    public TenantsRecord setSlug(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.tenants.slug</code>.
     */
    public String getSlug() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.tenants.status</code>.
     */
    public TenantsRecord setStatus(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.tenants.status</code>.
     */
    public String getStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.tenants.created_by</code>.
     */
    public TenantsRecord setCreatedBy(UUID value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.tenants.created_by</code>.
     */
    public UUID getCreatedBy() {
        return (UUID) get(4);
    }

    /**
     * Setter for <code>public.tenants.created_date</code>.
     */
    public TenantsRecord setCreatedDate(OffsetDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.tenants.created_date</code>.
     */
    public OffsetDateTime getCreatedDate() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>public.tenants.last_modified_by</code>.
     */
    public TenantsRecord setLastModifiedBy(UUID value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.tenants.last_modified_by</code>.
     */
    public UUID getLastModifiedBy() {
        return (UUID) get(6);
    }

    /**
     * Setter for <code>public.tenants.last_modified_date</code>.
     */
    public TenantsRecord setLastModifiedDate(OffsetDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.tenants.last_modified_date</code>.
     */
    public OffsetDateTime getLastModifiedDate() {
        return (OffsetDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TenantsRecord
     */
    public TenantsRecord() {
        super(Tenants.TENANTS);
    }

    /**
     * Create a detached, initialised TenantsRecord
     */
    public TenantsRecord(UUID id, String name, String slug, String status, UUID createdBy, OffsetDateTime createdDate, UUID lastModifiedBy, OffsetDateTime lastModifiedDate) {
        super(Tenants.TENANTS);

        setId(id);
        setName(name);
        setSlug(slug);
        setStatus(status);
        setCreatedBy(createdBy);
        setCreatedDate(createdDate);
        setLastModifiedBy(lastModifiedBy);
        setLastModifiedDate(lastModifiedDate);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised TenantsRecord
     */
    public TenantsRecord(com.mayuran19.mms.jooq.tables.pojos.Tenants value) {
        super(Tenants.TENANTS);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setSlug(value.getSlug());
            setStatus(value.getStatus());
            setCreatedBy(value.getCreatedBy());
            setCreatedDate(value.getCreatedDate());
            setLastModifiedBy(value.getLastModifiedBy());
            setLastModifiedDate(value.getLastModifiedDate());
            resetChangedOnNotNull();
        }
    }
}
