/*
 * This file is generated by jOOQ.
 */
package com.mayuran19.mms.jooq.tables.records;


import com.mayuran19.mms.jooq.tables.TenantUsers;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TenantUsersRecord extends UpdatableRecordImpl<TenantUsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.tenant_users.id</code>.
     */
    public TenantUsersRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.tenant_users.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.tenant_users.tenant_id</code>.
     */
    public TenantUsersRecord setTenantId(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.tenant_users.tenant_id</code>.
     */
    public UUID getTenantId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.tenant_users.email</code>.
     */
    public TenantUsersRecord setEmail(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.tenant_users.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.tenant_users.password_hash</code>.
     */
    public TenantUsersRecord setPasswordHash(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.tenant_users.password_hash</code>.
     */
    public String getPasswordHash() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.tenant_users.first_name</code>.
     */
    public TenantUsersRecord setFirstName(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.tenant_users.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.tenant_users.last_name</code>.
     */
    public TenantUsersRecord setLastName(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.tenant_users.last_name</code>.
     */
    public String getLastName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.tenant_users.status</code>.
     */
    public TenantUsersRecord setStatus(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.tenant_users.status</code>.
     */
    public String getStatus() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.tenant_users.created_by</code>.
     */
    public TenantUsersRecord setCreatedBy(UUID value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.tenant_users.created_by</code>.
     */
    public UUID getCreatedBy() {
        return (UUID) get(7);
    }

    /**
     * Setter for <code>public.tenant_users.created_date</code>.
     */
    public TenantUsersRecord setCreatedDate(OffsetDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.tenant_users.created_date</code>.
     */
    public OffsetDateTime getCreatedDate() {
        return (OffsetDateTime) get(8);
    }

    /**
     * Setter for <code>public.tenant_users.last_modified_by</code>.
     */
    public TenantUsersRecord setLastModifiedBy(UUID value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.tenant_users.last_modified_by</code>.
     */
    public UUID getLastModifiedBy() {
        return (UUID) get(9);
    }

    /**
     * Setter for <code>public.tenant_users.last_modified_date</code>.
     */
    public TenantUsersRecord setLastModifiedDate(OffsetDateTime value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.tenant_users.last_modified_date</code>.
     */
    public OffsetDateTime getLastModifiedDate() {
        return (OffsetDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TenantUsersRecord
     */
    public TenantUsersRecord() {
        super(TenantUsers.TENANT_USERS);
    }

    /**
     * Create a detached, initialised TenantUsersRecord
     */
    public TenantUsersRecord(UUID id, UUID tenantId, String email, String passwordHash, String firstName, String lastName, String status, UUID createdBy, OffsetDateTime createdDate, UUID lastModifiedBy, OffsetDateTime lastModifiedDate) {
        super(TenantUsers.TENANT_USERS);

        setId(id);
        setTenantId(tenantId);
        setEmail(email);
        setPasswordHash(passwordHash);
        setFirstName(firstName);
        setLastName(lastName);
        setStatus(status);
        setCreatedBy(createdBy);
        setCreatedDate(createdDate);
        setLastModifiedBy(lastModifiedBy);
        setLastModifiedDate(lastModifiedDate);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised TenantUsersRecord
     */
    public TenantUsersRecord(com.mayuran19.mms.jooq.tables.pojos.TenantUsers value) {
        super(TenantUsers.TENANT_USERS);

        if (value != null) {
            setId(value.getId());
            setTenantId(value.getTenantId());
            setEmail(value.getEmail());
            setPasswordHash(value.getPasswordHash());
            setFirstName(value.getFirstName());
            setLastName(value.getLastName());
            setStatus(value.getStatus());
            setCreatedBy(value.getCreatedBy());
            setCreatedDate(value.getCreatedDate());
            setLastModifiedBy(value.getLastModifiedBy());
            setLastModifiedDate(value.getLastModifiedDate());
            resetChangedOnNotNull();
        }
    }
}
